"""buddy notifications

Revision ID: 0104768267f8
Revises: 685a0520d96b
Create Date: 2026-06-07 18:35:27.854628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0104768267f8'
down_revision = '685a0520d96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buddy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buddy', schema=None) as batch_op:
        batch_op.drop_column('seen')

    # ### end Alembic commands ###
