"""earning notifications

Revision ID: 3b9d64241329
Revises: 0104768267f8
Create Date: 2026-06-07 19:03:59.318311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9d64241329'
down_revision = '0104768267f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.drop_column('seen')

    # ### end Alembic commands ###
