"""new staff

Revision ID: 57884b61a6fb
Revises: b2559224d749
Create Date: 2026-04-30 12:25:09.575697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57884b61a6fb'
down_revision = 'b2559224d749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like')
    # ### end Alembic commands ###
