"""add chat clear table

Revision ID: 5f3ae90776d8
Revises: 83935f36f3db
Create Date: 2026-09-27 20:10:39.919514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3ae90776d8'
down_revision = '83935f36f3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_clears',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('other_user_id', sa.Integer(), nullable=False),
    sa.Column('cleared_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_clears', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_clears_other_user_id'), ['other_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_clears_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_clears', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_clears_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_clears_other_user_id'))

    op.drop_table('chat_clears')
    # ### end Alembic commands ###
