"""'oncallclick'

Revision ID: 66971cf3afa4
Revises: 5f3ae90776d8
Create Date: 2026-10-04 17:15:43.478789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66971cf3afa4'
down_revision = '5f3ae90776d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('user_device_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_device_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_device_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_device_tokens_user_id'))

    op.drop_table('user_device_tokens')
    # ### end Alembic commands ###
