"""if any

Revision ID: 685a0520d96b
Revises: 35a2c4ef6b69
Create Date: 2026-06-06 19:12:12.393690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685a0520d96b'
down_revision = '35a2c4ef6b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_sender_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_receiver_id'))

    # ### end Alembic commands ###
