"""'chat'

Revision ID: 83935f36f3db
Revises: ce32ac73bf33
Create Date: 2026-09-19 17:01:09.083362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83935f36f3db'
down_revision = 'ce32ac73bf33'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'deleted_for_sender',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false()
            )
        )

        batch_op.add_column(
            sa.Column(
                'deleted_for_receiver',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false()
            )
        )

        batch_op.alter_column(
            'deleted_for_sender',
            server_default=None
        )

        batch_op.alter_column(
            'deleted_for_receiver',
            server_default=None
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_column('deleted_for_receiver')
        batch_op.drop_column('deleted_for_sender')

    # ### end Alembic commands ###
