"""name

Revision ID: a272c6a097ed
Revises: be545f6ff18d
Create Date: 2026-06-22 03:34:16.899391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a272c6a097ed'
down_revision = 'be545f6ff18d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buddy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buddy_name', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buddy', schema=None) as batch_op:
        batch_op.drop_column('buddy_name')

    # ### end Alembic commands ###
