"""empty message

Revision ID: aa54f8745141
Revises: 767c7b3d2205
Create Date: 2026-05-01 00:52:12.386036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa54f8745141'
down_revision = '767c7b3d2205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout', sa.Float(), nullable=True))
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('payout')

    # ### end Alembic commands ###
