"""'method'

Revision ID: ce32ac73bf33
Revises: 4bf3d200f7a2
Create Date: 2026-09-16 17:34:26.714846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce32ac73bf33'
down_revision = '4bf3d200f7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('paypal_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_request', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('paypal_email')
        batch_op.drop_column('method')

    # ### end Alembic commands ###
