"""bhg

Revision ID: e44ceda62698
Revises: a272c6a097ed
Create Date: 2026-06-24 21:08:02.015757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44ceda62698'
down_revision = 'a272c6a097ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###
